### ISSUE TITLE
create an index table without multiple records in the document table

### ISSUE THREAD

**Issue by nickaynes** [Lombiq/Orchard-Training-Demo-Module#10]
In the Book Index example you create    multiple book records in the documents table. 
How would i have only a single record in the documents table and multiple records in the index table. ?
I want to have a logentry.cs class in my index table but reference only 1 record in the documents table.

I don't want to pollute the documents table with hundreds of thousands of log entry records , since I have the log entry index table for this.
Can you give me an example ?
Thank you.

**Comment by barthamark** [comment]
I'd store log entries in another class as a list (e.g. Log.cs which as an `IList<LogEntry> LogEntries { get; set; }` property. It would make sure that there is only one document related to all the log entries (obviously it would be a large document but I assume this is what you meant by "reference only 1 record in the document table").

As for the index records the `IndexProvider` would be inherited from `IndexProvider<Log>` but in the `Describe` method you'd create the context for `LogEntry`. In the `Map` builder method you need to return the last `LogEntry` in the `Log.LogEntries` list (or if you add multiple `LogEntries` in the request then you can use the corresponding overload of the `Map` method where it can return multiple objects - in your case multiple `LogEntry` objects but make sure to not store duplicates). Let me know if it makes sense.

**Comment by nickaynes** [comment]
Yes, I get your point.
I am only concerned that the main record in the document table will become
huge and serializing it everytime with maybe millions of  logentry records
will impact performance.
Thanks.

**Comment by Piedone** [comment]
I don't think we can add anything else here, so closing the issue.
