### ISSUE TITLE
Discussion about a guide to getting started (OSOE-798)

### ISSUE THREAD

**Issue by MarGraz** [Lombiq/Orchard-Training-Demo-Module#132]
I'm continuing my learning path with Orchard Core and have some feedback that could be useful for the project. I've watched the [dojo course 3](https://www.youtube.com/watch?v=aSNRH-BDAdY&list=PLuskKJW0FhJcSX7j0Bd-1X5hq3dgCtYwO) on YouTube and explored [the code](https://github.com/Lombiq/Orchard-Training-Demo-Module?tab=readme-ov-file#how-to-start), but now, **I feel quite lost** 🫠

I've obtained a lot of information on **creating a module** and **handling events**, including **writing to the database**, I installed a clean Orchard on a Web App and I'm unsure (lost) about where to start. For instance:

1. Should I use a Blog/Agency recipe for creating a custom website, or would it be better to start with the blank recipe? 
2. What's the best practice to create my own theme and make it reusable? 
3. My website will feature two types of carousels, should I treat these as Orchard modules to be reused in other projects, or is it better to incorporate them into my theme? 🤔

Upon some search on Google, I discovered that **others have shared my confusion**. For example, this guy has written an [excellent guide](https://egoplacebo.medium.com/theming-orchard-core-d78c5cab1336) on theming Orchard Core from scratch, based on notes from a [five year old video](https://www.youtube.com/watch?v=wtAIgn4gYXc), which might still be relevant today (maybe needs to be updated).

I believe a beginner's guide to Orchard Core, **_with short tips on best practices for "Content Types"/"Content Parts" and theme creation, is crucial_**. Once familiar with the basics, developers can explore Orchard's deeper functionalities.

What are your thoughts?

Thank you

P.S. if this isn't the appropriate project for this discussion, could you show me where I can open this topic?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-798)

**Comment by Piedone** [comment]
Thanks for the well-thought-out points again! Indeed, this is not quite the right place to talk about these; your points are generic to Orchard Core, and not really about the Training Demo Module. Would you please copy this to the discussion board? https://github.com/OrchardCMS/OrchardCore/discussions If you link it here, I'll make sure to get back to you there.

BTW something you might have some feedback on too? https://github.com/Lombiq/Orchard-Training-Demo-Module/issues/131

**Comment by MarGraz** [comment]
@Piedone I moved the discussion [here](https://github.com/OrchardCMS/OrchardCore/discussions/15264)
