### ISSUE TITLE
InvalidOperationException: The partial view '/Areas/Lombiq.TrainingDemo/Views/InjectedShape.cshtml' was not found (OSOE-806)

### ISSUE THREAD

**Issue by JoJk0** [Lombiq/Orchard-Training-Demo-Module#133]
Hey, I'm trying to setup and run the project, particularly to see how `Orchard-Vue.js` works (via its samples).

- Long paths enabled via `LongPathsEnabled` setting to `1` in `regedit`
- Completed prerequisites for [NodeJs.Extensions](https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/Docs/SetupWindows.md)

Steps:

- Cloned https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions with `git clone`
- Recursive submodules with `git submodule update --init --recursive` inside the project directory
- Opened solution project in VS 2022 from the root project directory (**Lombiq.OSOCE.sln**)
- pressed `CTRL` + `F5` to build solution, node and pnpm seem to be ok
- once building finished, `https://localhost:5001/` opened with the setup page
- chose `Training Demo` as a setup recipe and `Sqlite` as a database
- Clicked `Finish setup`
- Received Internal Server Error (it persists even after quitting server and re-running it with `IIS express` button after initial setup)

```
InvalidOperationException: The partial view '/Areas/Lombiq.TrainingDemo/Views/InjectedShape.cshtml' was not found. The following locations were searched:
/Areas/Lombiq.TrainingDemo/Views/InjectedShape.cshtml
```

![image](https://github.com/Lombiq/Orchard-Training-Demo-Module/assets/10449993/dcc45bbd-f48e-417b-8531-b8b4c5b7fb97)

Is there anything I've missed and needs to be done?

I have Node.JS 20.10.0 installed via NVM and running it on Windows 11

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-806)

**Comment by Piedone** [comment]
Hmm, interesting, because the file is there and for me it also works, also with a fresh clone, doing the same steps, and the "I'm injected!" message appears as it should, too:

![image](https://github.com/Lombiq/Orchard-Training-Demo-Module/assets/1976647/c1882e3d-5151-4feb-8b26-abbf4332e2a6)

Can you confirm this file exists for you?

![image](https://github.com/Lombiq/Orchard-Training-Demo-Module/assets/1976647/946de493-527e-491f-a314-689eb7e9a64e)

Did you change anything in the code?

**Comment by JoJk0** [comment]
I've checked and it exists, I didn't touch the code, I started from scratch, fresh cloning and it's still the same. I've also tried to run setup of the project via headless recipe and it loaded but as soon as I activate training demo module from config panel it throws the same exception

**Comment by JoJk0** [comment]
I've also tried to do same setup with headless starting recipe, run `VueJs.Samples` recipe from the recipes panel and go to **Content Items** and click `New business card` button (or `Edit` button to existing business card). After that, similar exception occurs and the file actually exists:

![image](https://github.com/Lombiq/Orchard-Training-Demo-Module/assets/10449993/2a5439dd-abc8-4bdc-86f5-b37167257654)

**Comment by JoJk0** [comment]
Surprisingly it works via running `dotnet run` CLI command on `Lombiq.OSOCE.Web` and also after reinstalling VS so it appears like it was an issue with VS, thanks for your help anyway 🙂

**Comment by Piedone** [comment]
Great then! BTW I tried from VS, so the the CLI shouldn't be necessary.

**Comment by Piedone** [comment]
You may be interested in how I made this module easier to set up, without any dependencies apart from .NET: https://github.com/Lombiq/Orchard-Training-Demo-Module/issues/131.
