### ISSUE TITLE
AD0001 C# Analyzer threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

### ISSUE THREAD

**Issue by ziyadsv** [Lombiq/Orchard-Training-Demo-Module#15]
When i try to implement with latest Orchard Code .I got the above error.Its not building the page.

**Comment by Piedone** [comment]
Could you please try the issue/OCORE-13 branch?

**Comment by Piedone** [comment]
Since you didn't reply I'm assuming this was due to version incompatibility.

**Comment by ziyadsv** [comment]
Sorry for the late reply i was in aboard. Yeah its version incompatibility.Now working fine
