### ISSUE TITLE
Explaining Logging

### ISSUE THREAD

**Issue by Devqon** [Lombiq/Orchard-Training-Demo-Module#24]
In one of the first steps in the `YourFirstOrchardCoreController` it is explained that the `_logger` logs to a file through NLog.

When not using the OrchardCore source code, it should be explained that to get this working the developer should:
1. Install `OrchardCore.Logging.NLog` in the web application
2. Add an NLog.config
3. Add `ConfigureLogging()` to Program.cs

**Comment by Piedone** [comment]
It's easier to use the codegen template that offers this by default :). I've added emphasis for that to the Readme.
