### ISSUE TITLE
OrchardCore documentation links broken

### ISSUE THREAD

**Issue by Devqon** [Lombiq/Orchard-Training-Demo-Module#25]
The links to https://orchardcore.readthedocs.io/ are broken. For example in `YourFirstOrchardCoreController.cs` there is a link to https://orchardcore.readthedocs.io/en/latest/OrchardCore.Modules/OrchardCore.Localization/README/, which should probably be https://orchardcore.readthedocs.io/en/latest/docs/reference/modules/Localize/

**Comment by Piedone** [comment]
Would you mind submitting a PR for the broken links you encounter?

**Comment by Piedone** [comment]
Fixed them.
