### ISSUE TITLE
Training Demo Recipe not Showing

### ISSUE THREAD

**Issue by jason-delaplain** [Lombiq/Orchard-Training-Demo-Module#27]
I've struggled.  I haven't been able to get the "Training Demo" recipe to show when I start the site.  I have followed all the documentation, and I added the references to the orchardcore.application.targets, etc.  Am I missing something?

**Comment by Piedone** [comment]
It seems that yes, you do, otherwise it would work :). Did you try with the full source code or NuGet? Due to the source changing all the time the module can become incompatible. Then you can try the approach with packages.

**Comment by jason-delaplain** [comment]
Yea, that was rhetorical question lol.  I did it through full source code.  I'll check out trying using NuGet...

**Comment by Devqon** [comment]
I had the same issue when using the full source code. When starting a blank website and installing Orchard through NuGet the Demo module showed up.

**Comment by psijkof** [comment]
Either the source should be regularly update, so the recommendation can stand.
Otherwise I suggest the manual should recommend using NuGet packages.

**Comment by Piedone** [comment]
Hmm, were you actually using the latest released source of Orchard, i.e. the master branch, not the latest dev branch? Because now that I think about it that should fully work with the Training Demo.

**Comment by Piedone** [comment]
Oh wait, again the issue will be with the .NET Core version. Damn, .NET Core 3.0 getting unsupported within months really messed this up (we had to upgrade our modules but the latest released version of Orchard at the moment was built on 3.0). I'll update the docs.

**Comment by Piedone** [comment]
Updated the docs. And in the meantime, we've also released a repo with all our open-source extensions in a single bundle as a NuGet-using solution so from now on you don't even need to create a web app: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions
