### ISSUE TITLE
Had to Add OrchardCore.Contents Reference for AuthorizationController.cs

### ISSUE THREAD

**Issue by remesq** [Lombiq/Orchard-Training-Demo-Module#30]
Not sure if I missed something, but the AuthorizationController.cs was changed a while back and has a call to OrchardCore.Contents.Permissions.EditContent (line ~58). This was showing as an error in VS, but I fixed it by referencing OrchardCore.Contents as a project dependency.

**Comment by Piedone** [comment]
For now please use a solution with NuGet packages as described here: https://github.com/Lombiq/Orchard-Training-Demo-Module#using-a-full-orchard-core-source

**Comment by jwu-au** [comment]
I changed line 58 to below make it work with current Orchard Core in dev branch.
`if (!await _authorizationService.AuthorizeAsync(User, OrchardCore.Contents.CommonPermissions.EditContent, person))`

And also have to place the Vue and Training module in folder OrchardCore.Modules to make it works. Maybe it is out of topic, just noted here if you want it to run with latest Orchard Core.

**Comment by Piedone** [comment]
Thanks for both of you, I've added this to this collection issue: https://github.com/Lombiq/Orchard-Training-Demo-Module/issues/13
