### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jwu-au** [Lombiq/Orchard-Training-Demo-Module#31]
Lombiq.TrainingDemo\Indexing\ColorFieldIndexHandler.cs

> * IndexHandlers are different from IndexProviders. While IndexProviders will store indexed values in the SQL database

"While ~IndexProviders~" should be "While IndexHandlers" ?

**Comment by Piedone** [comment]
Hmm, I think this is correct. IndexProviders manage index records in an SQL table. IndexHandlers manage search indices. Probably it's a bit confusing what "these" refers to in the rest of the sentence so I made that clearer.

Thank you for opening the issue!
