### ISSUE TITLE
path Error

### ISSUE THREAD

**Issue by hyzx86** [Lombiq/Orchard-Training-Demo-Module#37]
https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/421bf42236f0ec5766be3caedfadd6ce169e769e/Gulpfile.babel.js#L32

must be
```
import getVueAppCompilerPipeline from '../Orchard-Vue.Js/Assets/Scripts/helpers/get-vue-app-compiler-pipeline';
```

**Comment by Piedone** [comment]
The folder referenced here is our Lombiq.VueJs module's. Why do you think it should be "Orchard-Vue.Js"?

**Comment by hyzx86** [comment]
The name of this Repository has been changed to Orchard-Vue.js , 
Maybe it was called Lombiq.VueJs before, but now the name is changed，
The folder name after the default clone is called Orchard-Vue.js

https://github.com/Lombiq/Orchard-Vue.js

**Comment by Piedone** [comment]
I see the confusion. While the repository is named like that the project's folder, as the project, should be named Lombiq.VueJs when you create it. But indeed we didn't document it.

**Comment by hyzx86** [comment]
Yes, this problem has troubled me for a lot of time, because I didn't read the error prompts carefully at first, and I'm not too familiar with gulp
Only finally found out that the path in the example project is wrong

**Comment by Piedone** [comment]
I see, I'm sorry about that. If you're confused please check out this repo that contains all projects: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions

Please reopen if you have any other issues.

**Comment by hyzx86** [comment]
No, I want to thank you for the Orchard-Training-Demo-Module Repository, it has been very helpful to me。 ：）

**Comment by Piedone** [comment]
I'm glad to hear that, Tony!
