### ISSUE TITLE
Vuejs Demo not work , and the main.js never used

### ISSUE THREAD

**Issue by hyzx86** [Lombiq/Orchard-Training-Demo-Module#38]
https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/479ab12016668a9163bf15ea7942651b778bdfcb/ResourceManifest.cs#L62

**Comment by Piedone** [comment]
Can you elaborate, please?

**Comment by hyzx86** [comment]
This path is wrong, there are no files in this path

![image](https://user-images.githubusercontent.com/15613121/85606073-5f0fd480-b685-11ea-9218-469fcb9fe15e.png)

I think the correct path should be here, but there is no demo.js, maybe the name was changed before.
Also, do we need to perform a copy of the contents in the Assets/apps/ directory in Gulpfile.babel.js?
I manually moved these files to the wwwroot folder and found that vue.js was missing.

**Comment by Piedone** [comment]
Those files are automatically built via Gulp and should appear in the wwwroot folder. If this doesn't happen for you then be sure to set up Node and Gulp as explained here: https://github.com/Lombiq/Orchard-Vue.js#prerequisites

**Comment by hyzx86** [comment]
Yes, I've done that, but I can't locate the VUE file, I've loaded it from the CDN instead
![image](https://user-images.githubusercontent.com/15613121/85607508-c417fa00-b686-11ea-83e7-5997c794264d.png)

**Comment by hyzx86** [comment]
Not yet, I'm trying to understand how Vue fits into Orchard Core. Does it dynamically render the shape of Orchard Core

**Comment by Piedone** [comment]
Can you verify that the NPM install and the build happens properly when you build in VS? Because everything should be added there.

**Comment by hyzx86** [comment]
Yes, if the compilation does not pass, OC will cann't run, because gulp is automatically executed in the project file, but now it is running, but some files cannot be found
![image](https://user-images.githubusercontent.com/15613121/85609329-8a47f300-b688-11ea-889e-18b27e225e9f.png)

**Comment by Piedone** [comment]
Hm, it seems to me that this is a passing build.  Vue compilation is also there correctly.

So I'm not sure what the issue here is. Is your problem that you don't see the Vue JS file anywhere? That's because it's installed from NPM in the Lombiq.VueJs module. In its package.json you can see Vue being referenced. The packages are installed with the `npm install` command executed during build.

**Comment by hyzx86** [comment]
Maybe I figured it out. I should have changed the Orchard-Vue.js folder to Lombiq.VueJs from the start

![image](https://user-images.githubusercontent.com/15613121/85692819-4ac0eb80-b708-11ea-80a7-f21befcc2cf9.png)


https://github.com/Lombiq/Orchard-Training-Demo-Module/issues/37

**Comment by Piedone** [comment]
Great then! Yeah, that's necessary. I've updated the docs in the meantime to make this step clearer.
