### ISSUE TITLE
Web API endpoint example

### ISSUE THREAD

**Issue by I3undy** [Lombiq/Orchard-Training-Demo-Module#4]
@Piedone created on Feb 20, 2014: 
https://orchardtrainingdemo.codeplex.com/workitem/10

Wouldn't be too complicated. Probably with dome demonstration on how to use the endpoints from JS and/or C#.

**Comment by Piedone** [comment]
This is interesting for Orchard Core too.

**Comment by Piedone** [comment]
This is interesting for Orchard Core too.
