### ISSUE TITLE
Suggestion: Possible to add multilingual using Content Localization?

### ISSUE THREAD

**Issue by Sen-Gupta** [Lombiq/Orchard-Training-Demo-Module#40]
Hi Lombiq team,

This demo modules looks like going to be very useful.
May I suggest, to add multilingual example using content localization?

**Comment by Piedone** [comment]
Hi! The module doesn't really deal with teaching user-facing features (which content localization is; what's developer-level there is mostly content definition but that the module talks about). However, you can check out this blog post of ours for info on content localization: https://orcharddojo.net/blog/how-to-localize-content-items-orchard-nuggets

**Comment by Sen-Gupta** [comment]
Hello,
What i meant is having a demo that contains how to grab multilingual content from API? 
The work may involve extending OrchardCore helper for Razor Syntax. 

We have already done it! I see it very important to have services available to serve headless implementations.
Could be a great learning as well.

I have been a tech instructor (Microsoft Certified Trainer) myself for more than 15 years and have trained people globally.

The course, seems to be doing good enough for somebody with a little OrchardCore background.
I was able to finish in less than 4 hours and did learn many patterns.

Thanks for all this hard work.

**Comment by Piedone** [comment]
I'm glad to hear the Training Demo was useful for you!

I'm still not sure I understand what exactly do you mean. Fetching localized versions fo content items via `IContentManager` and `ISession`? You say you've already done it, would you please submit a PR with examples you're suggesting?

**Comment by Piedone** [comment]
Please re-open if you can reply.
