### ISSUE TITLE
Get build error after install this module and VueJs module

### ISSUE THREAD

**Issue by lbcsy** [Lombiq/Orchard-Training-Demo-Module#43]
botnet build 

Build FAILED.

EXEC : { error : Cannot find module '../Lombiq.VueJs/Assets/Scripts/helpers/get-vue-app-compiler-pipeline' [/Users/bolin/dev/Orchard/Orchard-Training-Demo-Module/Lombiq.TrainingDemo.csproj]
/Users/bolin/dev/Orchard/Orchard-Training-Demo-Module/Lombiq.TrainingDemo.csproj(76,5): error MSB3073: The command "gulp" exited with code 1.
    0 Warning(s)
    2 Error(s)

Note: I am running VS 2019 for Mac

**Comment by Piedone** [comment]
Please install Node and Gulp as explained in the VueJs module's Readme. I'll also add a note to it here.

**Comment by Piedone** [comment]
Added it, thanks.

**Comment by lbcsy** [comment]
Hi Piedone, 
thanks for your reply. The Node and Gulp has been installed before I ran the build. See below the details of them:

xxx:Orchard-Training-Demo-Module yyy$ node --version
v10.8.0
xxx:Orchard-Training-Demo-Module yyy$ gulp --version
CLI version: 2.3.0
Local version: 4.0.2
xxx:Orchard-Training-Demo-Module yyy$ 

OrchardCore was on Master, demo module and Vue module were on dev.
Today, I change demo and Vue to master, now the error is different:

/Users/bolin/dev/Orchard/Orchard-Vue.js/Lombiq.VueJs.csproj: Error NU1201: Project OrchardCore.DisplayManagement is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project OrchardCore.DisplayManagement supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) (NU1201) (Lombiq.VueJs)

/Users/bolin/dev/Orchard/Orchard-Vue.js/Lombiq.VueJs.csproj: Error NU1201: Project OrchardCore.Module.Targets is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project OrchardCore.Module.Targets supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) (NU1201) (Lombiq.VueJs)

/Users/bolin/dev/Orchard/Orchard-Vue.js/Lombiq.VueJs.csproj: Error NU1201: Project OrchardCore.ResourceManagement is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project OrchardCore.ResourceManagement supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) (NU1201) (Lombiq.VueJs)

**Comment by Piedone** [comment]
Try to use the https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/ solution. Everything you need is in there and you don't need to care about versions. Please reopen if you still have issues there.
