### ISSUE TITLE
Outdated warning?

### ISSUE THREAD

**Issue by planetClaire** [Lombiq/Orchard-Training-Demo-Module#44]
Thanks for the awesome module. I think the warning below might be out of date since I had no problem using the module in this way:

"Warning: At the moment the latest released Orchard Core version is RC1 and it targets the unsupported 3.0 version of .NET Core. Since we updated our extensions to 3.1 they won't be compatible anymore. Thus for the time being please use the other approach with NuGet packages."

**Comment by Piedone** [comment]
I'm glad you like the module and thanks for the bug report!

Indeed, this was outdated, removed it.
