### ISSUE TITLE
OlderThan30 throwing an exception

### ISSUE THREAD

**Issue by planetClaire** [Lombiq/Orchard-Training-Demo-Module#45]
On /Lombiq.TrainingDemo/PersonList/OlderThan30 I'm getting 

InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Castle.Proxies.PersonPartViewModelProxy', but this ViewDataDictionary instance requires a model item of type 'OrchardCore.DisplayManagement.Views.ShapeViewModel`1[Lombiq.TrainingDemo.Models.PersonPart]'.

which I think must be related to 6958f27352d096e1184dd75eca3aefb9844b00b4

**Comment by Piedone** [comment]
Indeed, this was an error and got broken in the commit you referenced. Fixed it, could you confirm it, please?

**Comment by planetClaire** [comment]
Brilliant thank you 👍
