### ISSUE TITLE
TemplateContext.GlobalMemberAccessStrategy is undefined

### ISSUE THREAD

**Issue by hyzx86** [Lombiq/Orchard-Training-Demo-Module#59]
Is this code out of date?

https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/0004b296103f12e520f95d466b0ae7b513cf64d9/Startup.cs#L63

![image](https://user-images.githubusercontent.com/15613121/118750225-984ec580-b891-11eb-9fd9-5ff289ece02f.png)

**Comment by Piedone** [comment]
It might be with a newer version of Orchard we don't support yet. Are you using the module like this? https://github.com/Lombiq/Orchard-Training-Demo-Module#how-to-start

**Comment by hyzx86** [comment]
Yes, I did that by referring to the documentation.
And it's not just this one problem.


This is a new try（another computer） ,  I tried this library last year and it still worked. But when I recently updated the code and tried again, I found that it doesn't work

**Comment by hyzx86** [comment]
Sorry， I chose the wrong branch 。。
about Orchardcore, which branch should I choose?

**Comment by Piedone** [comment]
I really don't know what the issue could be. I just tried and it works for me, as it is working in our CI.

Please show the full Error List. Also, are you using the latest VS? Are NuGet restores working for you?

**Comment by hyzx86** [comment]
Visual Studio 2019 Version 16.9.4

I added this project to the OrchardCore source code project directory.

under the Path `OrchardCore\src\OrchardCore.Modules\Orchard-Training-Demo-Module`

![image](https://user-images.githubusercontent.com/15613121/120421459-eb983c00-c398-11eb-8aa0-5e6785ee7e18.png)

The package reference looks okay:
![image](https://user-images.githubusercontent.com/15613121/120421946-d5d74680-c399-11eb-9792-154ebbb54ef8.png)


![image](https://user-images.githubusercontent.com/15613121/120421542-14203600-c399-11eb-8528-34ceaf7589fc.png)

**Comment by Piedone** [comment]
Using the full Orchard source is not a supported scenario anymore. Please use the Open-Source Orchard Core Extensions repository as explained under https://github.com/Lombiq/Orchard-Training-Demo-Module#how-to-start
