### ISSUE TITLE
Step-by-step setup for training demo module

### ISSUE THREAD

**Issue by devlife** [Lombiq/Orchard-Training-Demo-Module#70]
I'm trying to get everything setup and building for the training demo module. This seems to be more complex than I would have expected. Even after cloning the utilities, the Libraries, pnpm, and everything else I'm still having issues. Would it be possible to provide a step-by-step list of instructions so a developer can get things setup so it builds/runs properly (including orchard core source)?

**Comment by Piedone** [comment]
Did you follow https://github.com/Lombiq/Orchard-Training-Demo-Module#how-to-start? Using the full OC source is not supported anymore.

**Comment by devlife** [comment]
Ah it seems the instructions changed since the last time I did this. I'll checkout a fresh clone and see how it goes.

**Comment by Piedone** [comment]
Did it work for you in the end?

**Comment by Piedone** [comment]
Just please reopen if you have further questions.

**Comment by Piedone** [comment]
You may be interested in how I made this module easier to set up, without any dependencies apart from .NET: https://github.com/Lombiq/Orchard-Training-Demo-Module/issues/131.

**Comment by devlife** [comment]
Thanks @Piedone! I'll check it out. As it turns out I'm currently on a machine without this repo on it.
