### ISSUE TITLE
How to use DisplayDriver when using widgets/flow editor

### ISSUE THREAD

**Issue by devlife** [Lombiq/Orchard-Training-Demo-Module#72]
I have a ContentPart (with a widget stereo type), a ViewModel, a DisplayDriver which returns the ViewModel from `Display`, and added the widget to a flow editor in a Page. However, when I go to run the site, it appears that the widget file (Widget-MyComponent.cshtml) requires a model of type `ZoneHolding` isntead of the ViewModel. If that is the case, how would I update `DisplayDriver.Display` to return a ZoneHolding instead of the ViewModel? I'm a bit confused as to how all of this works.

**Comment by Piedone** [comment]
This looks like a question about Orchard and not about the Training Demo module. Could you ask it here instead, since here it's better suited? https://github.com/OrchardCMS/OrchardCore/discussions

**Comment by devlife** [comment]
Will do.

**Comment by Piedone** [comment]
Thanks!
