### ISSUE TITLE
Module does not compile and references Orchard instead of OrchardCore

### ISSUE THREAD

**Issue by psijkof** [Lombiq/Orchard-Training-Demo-Module#8]
Tried to follow the read me but it doesn't compile to the reason stated in the subject

**Comment by Piedone** [comment]
The module has two versions, one for Orchard 1.x and one for Orchard Core. As also linked in the Readme the Core version is in the orchard-core branch: https://github.com/Lombiq/Orchard-Training-Demo-Module/tree/orchard-core
