### ISSUE TITLE
Orchard.Core missing project reference to Lombiq.VueJs.csproj

### ISSUE THREAD

**Issue by nickaynes** [Lombiq/Orchard-Training-Demo-Module#9]
The orchardcore branch does not compile due to a missing project reference to  Lombiq.VueJs.csproj.
thanks.

**Comment by Piedone** [comment]
As explained in the Readme, you need to add the Lombiq.VueJs module to your solution as well, since the VueJS sample depends on it.

**Comment by giannik** [comment]
sorry, missed it.

**Comment by nickaynes** [comment]
sorry, missed it.
